const data = [
  {
    "Title": "A Comparative Analysis of Gene Expression Profiles during Skin Regeneration in Mus and Acomys",
    "signal pathway": "Tgf-β, ECM remodeling, inflammatory cytokines",
    "RNAseq/proteomic": "Microarray (GEO GSE74387)",
    "First author": "Jason Orr Brant",
    "Affiliation": "University of Florida",
    "Journal": "PLoS ONE",
    "Year": 2015,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1371/journal.pone.0142931",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "A comparative study of renal function in the desert-adapted spiny mouse and the laboratory-adapted C57BL/6 mouse: response to dietary salt load",
    "signal pathway": "Not specified",
    "RNAseq/proteomic": null,
    "First author": "Hayley Dickinson",
    "Affiliation": "Monash University",
    "Journal": "American Journal of Physiology - Renal Physiology",
    "Year": 2007,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1152/ajprenal.00202.2007",
    "Topic": "Metabolism / Kidney",
    "Organ": "Kidney",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "A comparative study of sleep and diurnal patterns in house mouse (Mus musculus) and Spiny mouse (Acomys cahirinus)",
    "signal pathway": "Not specified",
    "RNAseq/proteomic": null,
    "First author": "Chanung Wang",
    "Affiliation": "University of Kentucky",
    "Journal": "Scientific Reports",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1038/s41598-020-67859-w",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "A human-based assisted reproduction protocol for the menstruating spiny mouse, Acomys cahirinus",
    "signal pathway": "GnRH, FSH, hCG (endocrine signaling)",
    "RNAseq/proteomic": null,
    "First author": "Jarrod McKenna",
    "Affiliation": "Monash University",
    "Journal": "PLOS ONE",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1371/journal.pone.0244411",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "A missing piece: the spiny mouse and the puzzle of menstruating species",
    "signal pathway": "Progesterone, prolactin",
    "RNAseq/proteomic": null,
    "First author": "Nadia Bellofiore",
    "Affiliation": "Hudson Institute of Medical Research, Monash University",
    "Journal": "Journal of Molecular Endocrinology",
    "Year": 2018,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1530/JME-17-0278",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "A New Coccidian from Acomys cahirinus Desmarest, 1819, from Evolution Canyon, Lower Nahal Oren, Mount Carmel, Israel",
    "signal pathway": "Not applicable",
    "RNAseq/proteomic": null,
    "First author": "Lee Couch",
    "Affiliation": "University of New Mexico",
    "Journal": "Journal of Parasitology",
    "Year": 1997,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.2307/3284556",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Mexico"
  },
  {
    "Title": "A profusion of neural stem cells in the brain of the spiny mouse, Acomys cahirinus",
    "signal pathway": "Wnt, Shh, BMP, Notch",
    "RNAseq/proteomic": null,
    "First author": "Malcolm Maden",
    "Affiliation": "University of Florida",
    "Journal": "Journal of Anatomy",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1111/joa.13373",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Acomys, the closest relatives to Gerbils, do express Pdx-1 protein and have similar islet morphology to Gerbils",
    "signal pathway": "Pdx-1",
    "RNAseq/proteomic": null,
    "First author": "Carsten R. Gustavsen",
    "Affiliation": "Hagedorn Research Institute",
    "Journal": "Islets",
    "Year": 2009,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.4161/isl.1.3.9557",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Denmark"
  },
  {
    "Title": "Adaptations in Hippo-Yap signaling and myofibroblast fate underlie scar-free ear appendage wound healing in spiny mice",
    "signal pathway": "Hippo-Yap",
    "RNAseq/proteomic": "transcriptomics (GSE224879, GSE224433) ",
    "First author": "Chris M. Brewer",
    "Affiliation": "University of Washington / Seattle Children’s Research Institute",
    "Journal": "Developmental Cell",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Unknown",
    "DOI": "10.1016/j.devcel.2021.09.008",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Adrenal steroidogenesis following prenatal dexamethasone exposure in the spiny mouse",
    "signal pathway": "HPA axis, ACTH, P450C17, CYTB5",
    "RNAseq/proteomic": null,
    "First author": "Tracey A Quinn",
    "Affiliation": "Monash University",
    "Journal": "Journal of Endocrinology",
    "Year": 2014,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1530/JOE-13-0514",
    "Topic": "Metabolism / Kidney",
    "Organ": "Kidney",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Adult spiny mice (Acomys) exhibit endogenous cardiac recovery in response to myocardial infarction",
    "signal pathway": "Endothelial proliferation, angiogenesis (general signaling not deeply specified)",
    "RNAseq/proteomic": null,
    "First author": "Hsuan Peng",
    "Affiliation": "University of Kentucky",
    "Journal": "NPJ Regenerative Medicine",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1038/s41536-021-00186-4",
    "Topic": "Regeneration",
    "Organ": "Heart",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "African Spiny Mice (Acomys) Exhibit Mild Osteoarthritis Following Meniscal Injury",
    "signal pathway": "Not specified",
    "RNAseq/proteomic": null,
    "First author": "Kiara M. Chan",
    "Affiliation": "University of Florida",
    "Journal": "Cartilage",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1177/19476035221149146",
    "Topic": "Musculoskeletal",
    "Organ": "Other",
    "Disease Model": "Bone / Joint Disorders",
    "Country": "USA"
  },
  {
    "Title": "Albert Renold Memorial Lecture: Molecular Background of Nutritionally Induced Insulin Resistance Leading to Type 2 Diabetes",
    "signal pathway": "Insulin receptor, PKCε, GLUT4, tyrosine kinase pathway",
    "RNAseq/proteomic": null,
    "First author": "Eleazar Shafrir",
    "Affiliation": "Hebrew University-Hadassah Medical School",
    "Journal": "International Journal of Experimental Diabetes Research",
    "Year": 2001,
    "Proteomics accession": null,
    "Species": "Unknown",
    "DOI": "10.1080/15604280110038502",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Diabetes / Metabolic Syndrome",
    "Country": "Israel"
  },
  {
    "Title": "Altered exploratory behaviour and increased food intake in the spiny mouse before menstruation",
    "signal pathway": "Progesterone withdrawal, prostaglandins, IL-8, MMP-3/-9",
    "RNAseq/proteomic": null,
    "First author": "Nadia Bellofiore",
    "Affiliation": "Hudson Institute of Medical Research, Monash University",
    "Journal": "Human Reproduction",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1093/humrep/dey360",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "An ERK-dependent molecular switch antagonizes fibrosis and promotes regeneration in spiny mice (Acomys)",
    "signal pathway": "ERK, FGF, ErbB signaling",
    "RNAseq/proteomic": "RNAseq/scRNAseq (GSE224879/GSE224433) ",
    "First author": "Antonio Tomasso",
    "Affiliation": "Max Planck Institute for Molecular Biomedicine",
    "Journal": "Science Advances",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1126/sciadv.adf2331",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "Germany"
  },
  {
    "Title": "Apparatus for Collection of Fecal Samples from Undisturbed Spiny Mice (Acomys cahirinus)",
    "signal pathway": "Glucocorticoid metabolism",
    "RNAseq/proteomic": null,
    "First author": "Daniel Frynta",
    "Affiliation": "Charles University",
    "Journal": "Journal of the American Association for Laboratory Animal Science",
    "Year": 2009,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": null,
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Czech Republic"
  },
  {
    "Title": "Audiograms of five species of rodents: implications for the evolution of hearing and the perception of pitch",
    "signal pathway": "Not applicable",
    "RNAseq/proteomic": null,
    "First author": "R.S. Heffner",
    "Affiliation": "University of Toledo",
    "Journal": "Hearing Research",
    "Year": 2001,
    "Proteomics accession": null,
    "Species": "Unknown",
    "DOI": "10.1016/S0378-5955(01)00298-2",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Babesia behnkei sp. nov., a novel Babesia species infecting isolated populations of Wagner’s gerbil",
    "signal pathway": "Not applicable (parasitology focus)",
    "RNAseq/proteomic": null,
    "First author": "Anna Bajer",
    "Affiliation": "University of Warsaw",
    "Journal": "Parasites & Vectors",
    "Year": 2014,
    "Proteomics accession": null,
    "Species": "Dipodillus",
    "DOI": "10.1186/s13071-014-0572-9",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Poland"
  },
  {
    "Title": "Behaviour and hippocampus-specific changes in spiny mouse neonates after treatment of the mother with Poly I:C at mid-pregnancy",
    "signal pathway": "Cytokines, microglia, GFAP, Reelin",
    "RNAseq/proteomic": null,
    "First author": "Udani Ratnayake",
    "Affiliation": "Monash University",
    "Journal": "Brain, Behavior, and Immunity",
    "Year": 2012,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.bbi.2012.08.011",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Betaherpesvirus Sequences in Eastern Spiny Mice and Wagner’s Dipodils",
    "signal pathway": "Herpesvirus-host immune modulation",
    "RNAseq/proteomic": null,
    "First author": "Rachael E. Tarlinton",
    "Affiliation": "University of Nottingham",
    "Journal": "Journal of Wildlife Diseases",
    "Year": 2011,
    "Proteomics accession": null,
    "Species": "Unknown",
    "DOI": "10.7589/0090-3558-47.4.958",
    "Topic": "Immunology",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "UK"
  },
  {
    "Title": "Biased brain and behavioral responses towards kin in males of a communally breeding species",
    "signal pathway": "Lateral septum (LS), kin recognition circuits",
    "RNAseq/proteomic": null,
    "First author": "Brandon A. Fricker",
    "Affiliation": "Emory University",
    "Journal": "Scientific Reports",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1038/s41598-023-44257-6",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Bite Wounds and Dominance Structures in Male and Female African Spiny Mice (Acomys cahirinus)",
    "signal pathway": "Immune/inflammatory response (mentioned indirectly)",
    "RNAseq/proteomic": null,
    "First author": "Justin A. Varholick",
    "Affiliation": "University of Florida",
    "Journal": "Animals",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.3390/ani14010064",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Breathing patterns and CO2 production in adult spiny mice (Acomys cahirinus)",
    "signal pathway": "Hypoxia/hypercapnia response (respiratory neural pathways)",
    "RNAseq/proteomic": null,
    "First author": "Sabhya Rana",
    "Affiliation": "University of Florida",
    "Journal": "Respiratory Physiology & Neurobiology",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1016/j.resp.2022.103975",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Ischemia / Stroke",
    "Country": "USA"
  },
  {
    "Title": "Cellular events during scar-free skin regeneration in the spiny mouse, Acomys",
    "signal pathway": "Inflammatory cytokines, macrophage absence, ECM regulation",
    "RNAseq/proteomic": null,
    "First author": "Jason O. Brant",
    "Affiliation": "University of Florida",
    "Journal": "Wound Repair and Regeneration",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1111/wrr.12385",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Characterization of human-like menstruation in the spiny mouse: comparative studies with the human and induced mouse model",
    "signal pathway": "IL-8, IL-11, VEGF, MIF",
    "RNAseq/proteomic": null,
    "First author": "Nadia Bellofiore",
    "Affiliation": "Hudson Institute of Medical Research, Monash University",
    "Journal": "Human Reproduction",
    "Year": 2018,
    "Proteomics accession": null,
    "Species": "Acomys, Mus, Human",
    "DOI": "10.1093/humrep/dey247",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "Cingulate to septal circuitry facilitates the preference to affiliate with large peer groups",
    "signal pathway": "ACC-LS circuit, social behavior",
    "RNAseq/proteomic": null,
    "First author": "Brandon A. Fricker",
    "Affiliation": "Emory University",
    "Journal": "Current Biology",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.cub.2024.08.019",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Circadian activity rhythms in the spiny mouse, Acomys cahirinus",
    "signal pathway": "Suprachiasmatic nucleus (SCN), circadian control",
    "RNAseq/proteomic": null,
    "First author": "E.T. Weber",
    "Affiliation": "Rider University",
    "Journal": "Physiology & Behavior",
    "Year": 2005,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.physbeh.2005.07.023",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Comparative analysis of Acomys cahirinus and Mus musculus responses to genotoxicity, oxidative stress, and inflammation",
    "signal pathway": "CXCL1, IL-1β, Notch2, TNF-α",
    "RNAseq/proteomic": null,
    "First author": "Lamees N. Ghebryal",
    "Affiliation": "Cairo University",
    "Journal": "Scientific Reports",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1038/s41598-023-31143-4",
    "Topic": "Immunology",
    "Organ": "Other",
    "Disease Model": "Infection / Immune",
    "Country": "Egypt"
  },
  {
    "Title": "Comparative analysis of ear-hole closure identifies epimorphic regeneration as a discrete trait in mammals",
    "signal pathway": "Blastema formation, cell cycle progression",
    "RNAseq/proteomic": "RNAseq (GSE71761)",
    "First author": "Thomas R. Gawriluk",
    "Affiliation": "University of Kentucky",
    "Journal": "Nature Communications",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys, Mus, Rabbit",
    "DOI": "10.1038/ncomms11164",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Comparative non-shivering thermogenesis in adjacent populations of the common spiny mouse (Acomys cahirinus)",
    "signal pathway": "UCP1, brown adipose tissue",
    "RNAseq/proteomic": null,
    "First author": "Yael Zizmor",
    "Affiliation": "Hebrew University of Jerusalem",
    "Journal": "Comparative Biochemistry and Physiology Part A",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.cbpa.2019.110541",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Jerusalem"
  },
  {
    "Title": "Comparative Proteomic Analysis in Scar-Free Skin Regeneration in Acomys cahirinus and Scarring Mus musculus",
    "signal pathway": "Wnt, MAPK, ECM-receptor, ubiquitin, tight junction",
    "RNAseq/proteomic": "proteomics",
    "First author": "Jung Hae Yoon",
    "Affiliation": "University of Florida",
    "Journal": "Scientific Reports",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1038/s41598-019-56823-y",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Comparative regenerative biology of spiny (Acomys cahirinus) and laboratory (Mus musculus) mouse skin",
    "signal pathway": "Stem cell markers K15, CD34",
    "RNAseq/proteomic": "No",
    "First author": "Ting-Xin Jiang",
    "Affiliation": "University of Southern California",
    "Journal": "Experimental Dermatology",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1111/exd.13899",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Comparative review of the brain development in Acomys cahirinus",
    "signal pathway": "Neurogenesis, Ki-67, doublecortin, BrdU",
    "RNAseq/proteomic": "No",
    "First author": "Natalia Merkulyeva",
    "Affiliation": "Pavlov Institute of Physiology, Russian Academy of Sciences",
    "Journal": "Neuroscience and Biobehavioral Reviews",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.neubiorev.2024.105939",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "Russia"
  },
  {
    "Title": "Comparative transcriptomic analysis of dermal wound healing reveals de novo skeletal muscle regeneration in Acomys cahirinus",
    "signal pathway": "Wnt7a, Wnt2, Wnt6, Il10, Col6a1",
    "RNAseq/proteomic": "RNAseq (GSE113081)",
    "First author": "Jason O. Brant",
    "Affiliation": "University of Florida",
    "Journal": "PLOS ONE",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.1371/journal.pone.0216228",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Complex Tissue Regeneration in Mammals Is Associated With Reduced Inflammatory Cytokines and an Influx of T Cells",
    "signal pathway": "IL-6, CCL2, CXCL1, IL-12, IL-17, T cell signaling",
    "RNAseq/proteomic": null,
    "First author": "Thomas R. Gawriluk",
    "Affiliation": "University of Kentucky",
    "Journal": "Frontiers in Immunology",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys, Mus",
    "DOI": "10.3389/fimmu.2020.01695",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Connective tissue fibroblasts from highly regenerative mammals are refractory to ROS-induced cellular senescence",
    "signal pathway": "p53, p21, p16, p19, oxidative stress pathways",
    "RNAseq/proteomic": null,
    "First author": "Sandeep Saxena",
    "Affiliation": "University of Kentucky",
    "Journal": "Nature Communications",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys, Mus, Rattus, Oryctolagus",
    "DOI": "10.1038/s41467-019-12398-w",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Aging",
    "Country": "USA"
  },
  {
    "Title": "Coronal brain atlas in stereotaxic coordinates of the African spiny mouse, Acomys cahirinus",
    "signal pathway": "Not specified (neuroanatomical atlas)",
    "RNAseq/proteomic": null,
    "First author": "Marta Vitorino",
    "Affiliation": "University of Algarve",
    "Journal": "Journal of Comparative Neurology",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1002/cne.25329",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "Portugal"
  },
  {
    "Title": "Creatine pretreatment prevents birth asphyxia–induced injury of the newborn spiny mouse kidney",
    "signal pathway": "HIF1α, BAX, BCL2, LCN2, nephrin",
    "RNAseq/proteomic": null,
    "First author": "Zoe Ireland",
    "Affiliation": "Monash University",
    "Journal": "Pediatric Research",
    "Year": 2013,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1038/pr.2012.180",
    "Topic": "Other",
    "Organ": "Kidney",
    "Disease Model": "Ischemia / Stroke",
    "Country": "Australia"
  },
  {
    "Title": "De novo transcriptome assembly for the spiny mouse (Acomys cahirinus)",
    "signal pathway": "Transcriptome resource, general gene expression",
    "RNAseq/proteomic": "RNAseq (PRJNA292021, GSE71761)",
    "First author": "Jared Mamrot",
    "Affiliation": "Hudson Institute of Medical Research, Monash University",
    "Journal": "Scientific Reports",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1038/s41598-017-09334-7",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Developmental changes in the expression of creatine synthesizing enzymes and creatine transporter in a precocial rodent, the spiny mouse",
    "signal pathway": "AGAT, GAMT, CrT, creatine pathway",
    "RNAseq/proteomic": null,
    "First author": "Zoe Ireland",
    "Affiliation": "Monash University",
    "Journal": "BMC Developmental Biology",
    "Year": 2009,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1186/1471-213X-9-39",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Dietary creatine supplementation during pregnancy: effects on creatine homeostasis and renal excretory function in spiny mice",
    "signal pathway": "Creatine biosynthesis pathway (AGAT, GAMT, CrT1)",
    "RNAseq/proteomic": null,
    "First author": "Stacey J. Ellery",
    "Affiliation": "Hudson Institute of Medical Research, Monash University",
    "Journal": "Amino Acids",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1007/s00726-015-2150-7",
    "Topic": "Metabolism / Kidney",
    "Organ": "Kidney",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Distinct Hemostasis and Blood Composition in Spiny Mouse Acomys cahirinus",
    "signal pathway": "Hemostasis signaling, fibrinogen pathways",
    "RNAseq/proteomic": null,
    "First author": "Nikita S. Filatov",
    "Affiliation": "Kazan Federal University",
    "Journal": "International Journal of Molecular Sciences",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.3390/ijms252312867",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Russia"
  },
  {
    "Title": "Distribution of vasopressin 1a and oxytocin receptor protein and mRNA in the basal forebrain and midbrain of the spiny mouse",
    "signal pathway": "OXTR, AVPR1A signaling",
    "RNAseq/proteomic": null,
    "First author": "Jeanne M. Powell",
    "Affiliation": "Emory University",
    "Journal": "Brain Structure and Function",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1007/s00429-022-02581-z",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Distribution of vasopressin and oxytocin neurons in the basal forebrain and midbrain of spiny mice (Acomys cahirinus)",
    "signal pathway": "Vasopressin, oxytocin neuronal distribution",
    "RNAseq/proteomic": null,
    "First author": "Aubrey M. Kelly",
    "Affiliation": "Emory University",
    "Journal": "Neuroscience",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.neuroscience.2021.05.034",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "DNA methylation networks underlying mammalian traits",
    "signal pathway": "HOXL subclass homeobox, ASCL1, SMAD6, OCT4, SOX2, NANOG, POLII, CTCF, RAD21, YY1, TAF1",
    "RNAseq/proteomic": "DNA methylation (GSE223748)",
    "First author": "Amin Haghani",
    "Affiliation": "Altos Labs",
    "Journal": "Science",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus (among 348 mammals)",
    "DOI": "10.1126/science.abq5693",
    "Topic": "Epigenetics",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Ear wound regeneration in the African spiny mouse Acomys cahirinus",
    "signal pathway": "Angiogenesis, blastema formation",
    "RNAseq/proteomic": null,
    "First author": "Dino Matias Santos",
    "Affiliation": "University of Algarve",
    "Journal": "Regeneration",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1002/reg2.50",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "Portugal"
  },
  {
    "Title": "Effect of conspecific and heterospecific urine odors on the foraging behavior of the golden spiny mouse",
    "signal pathway": "Olfactory/pheromonal signaling",
    "RNAseq/proteomic": null,
    "First author": "Claude Baudoin",
    "Affiliation": "University of Paris 13",
    "Journal": "Integrative Zoology",
    "Year": 2013,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1111/j.1749-4877.2012.00291.x",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Aging",
    "Country": "France"
  },
  {
    "Title": "Effect of food availability and leptin on the physiology and hypothalamic gene expression of the golden spiny mouse",
    "signal pathway": "Leptin, NPY, AgRP, POMC, CART",
    "RNAseq/proteomic": null,
    "First author": "Roee Gutman",
    "Affiliation": "Tel Aviv University",
    "Journal": "American Journal of Physiology - Regulatory, Integrative and Comparative Physiology",
    "Year": 2008,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1152/ajpregu.00105.2008",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Effect of increased dietary salinity on the reproductive status and energy intake of xeric and mesic populations of the spiny mouse, Acomys",
    "signal pathway": "Vasopressin signaling, osmoregulation",
    "RNAseq/proteomic": null,
    "First author": "Tilaye Wube",
    "Affiliation": "University of Haifa",
    "Journal": "Physiology & Behavior",
    "Year": 2009,
    "Proteomics accession": null,
    "Species": "Acomys russatus, Acomys cahirinus",
    "DOI": "10.1016/j.physbeh.2008.09.006",
    "Topic": "Reproduction",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Effects of High-protein and High-fiber Diets on Weight and Glucose Regulation in Spiny Mice (Acomys cahirinus)",
    "signal pathway": "Glucose-insulin regulation",
    "RNAseq/proteomic": null,
    "First author": "Joette W. Crews",
    "Affiliation": "Emory University",
    "Journal": "Journal of the American Association for Laboratory Animal Science",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.30802/AALAS-JAALAS-23-000112",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Diabetes / Metabolic Syndrome",
    "Country": "USA"
  },
  {
    "Title": "Epigenetic predictors of species maximum life span and other life-history traits in mammals",
    "signal pathway": "Somatotropic axis, pluripotency (OCT4, SOX2, NANOG), POLII, CTCF, RAD21, YY1, TAF1",
    "RNAseq/proteomic": "DNA methylation (GSE223748)",
    "First author": "Caesar Z. Li",
    "Affiliation": "University of California, Los Angeles",
    "Journal": "Science Advances",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus (among 348 mammals)",
    "DOI": "10.1126/sciadv.adm7273",
    "Topic": "Epigenetics",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Evaluation of 3K3A-Activated Protein C to Treat Neonatal Hypoxic Ischemic Brain Injury in the Spiny Mouse",
    "signal pathway": "TGFβ1, inflammation, apoptosis",
    "RNAseq/proteomic": null,
    "First author": "Stacey J. Ellery",
    "Affiliation": "Hudson Institute of Medical Research",
    "Journal": "Neurotherapeutics",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1007/s13311-018-0661-0",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Infection / Immune",
    "Country": "Australia"
  },
  {
    "Title": "Exploring the role of microRNAs in axolotl regeneration",
    "signal pathway": "miRNA regulation of regeneration (e.g., Hedgehog, cytokine pathways)",
    "RNAseq/proteomic": null,
    "First author": "Haitham G. Abo‐Al‐Ela",
    "Affiliation": "Suez University",
    "Journal": "Journal of Cellular Physiology",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Axolotl",
    "DOI": "10.1002/jcp.29920",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Other / Not Specified",
    "Country": "Egypt"
  },
  {
    "Title": "Femoral µCT Analysis, Mechanical Testing and Immunolocalization of Bone Proteins in HMB Supplemented Spiny Mouse",
    "signal pathway": "Bone morphogenetic protein 2 (BMP-2), TIMP-2, MMP-8, MMP-13",
    "RNAseq/proteomic": null,
    "First author": "Ewa Tomaszewska",
    "Affiliation": "University of Life Sciences in Lublin",
    "Journal": "Journal of Clinical Medicine",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.3390/jcm10214808",
    "Topic": "Musculoskeletal",
    "Organ": "Muscle / Bone",
    "Disease Model": "Other / Not Specified",
    "Country": "Poland"
  },
  {
    "Title": "Fitness consequences of chronic exposure to different light pollution wavelengths in nocturnal and diurnal rodents",
    "signal pathway": "Circadian, glucocorticoid signaling",
    "RNAseq/proteomic": null,
    "First author": "Hagar Vardi‐Naim",
    "Affiliation": "Tel Aviv University",
    "Journal": "Scientific Reports",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Acomys russatus",
    "DOI": "10.1038/s41598-022-19805-1",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Foraging sequence, energy intake and torpor in desert golden spiny mice",
    "signal pathway": "Torpor regulation, energy balance",
    "RNAseq/proteomic": null,
    "First author": "Ofir Levy",
    "Affiliation": "Tel Aviv University",
    "Journal": "Ecology Letters",
    "Year": 2012,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1111/j.1461-0248.2012.01845.x",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Aging",
    "Country": "Israel"
  },
  {
    "Title": "Gastrointestinal nematode community of spiny mice (Acomys dimidiatus) from South Sinai",
    "signal pathway": "Host-parasite immune interaction (indirectly)",
    "RNAseq/proteomic": null,
    "First author": "Maha F. M. Soliman",
    "Affiliation": "Suez Canal University",
    "Journal": "Journal of Parasitic Diseases",
    "Year": 2015,
    "Proteomics accession": null,
    "Species": "Acomys dimidiatus",
    "DOI": "10.1007/s12639-013-0410-6",
    "Topic": "Immunology",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "Egypt"
  },
  {
    "Title": "Gene expression defines natural changes in mammalian lifespan",
    "signal pathway": "AMPK, PPAR, TCA cycle, GH/GHR, mitochondrial metabolism, DNA repair (NHEJ), oxidative stress",
    "RNAseq/proteomic": "review_RNAseq (GSE43013, PRJNA182705)",
    "First author": "Alexey A. Fushan",
    "Affiliation": "Ewha Womans University",
    "Journal": "Aging Cell",
    "Year": 2015,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus (among 33 mammals)",
    "DOI": "10.1111/acel.12283",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Aging",
    "Country": "South Korea"
  },
  {
    "Title": "Generation and characterization of two immortalized dermal fibroblast cell lines from the spiny mouse (Acomys)",
    "signal pathway": "ECM deposition, fibroblast markers",
    "RNAseq/proteomic": "Proteomics",
    "First author": "Michele N. Dill",
    "Affiliation": "University of Florida",
    "Journal": "PLOS ONE",
    "Year": 2023,
    "Proteomics accession": "Mendeley: nxdrvfphzz",
    "Species": "Acomys",
    "DOI": "10.1371/journal.pone.0280169",
    "Topic": "Other",
    "Organ": "Skin",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Genome Report: chromosome-scale genome assembly of the African spiny mouse (Acomys cahirinus)",
    "signal pathway": "Genomic basis of regeneration",
    "RNAseq/proteomic": "RNAseq (PRJNA342864)",
    "First author": "Elizabeth Dong Nguyen",
    "Affiliation": "University of Washington",
    "Journal": "G3: Genes, Genomes, Genetics",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1093/g3journal/jkad177",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Good things come to those who mate: analysis of the mating behaviour in the menstruating rodent, Acomys cahirinus",
    "signal pathway": "Reproductive hormone regulation",
    "RNAseq/proteomic": null,
    "First author": "Jarrod McKenna",
    "Affiliation": "Monash University",
    "Journal": "BMC Zoology",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1186/s40850-022-00112-1",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "Helminths Collected From Imported Pet Murids, with Special Reference to Concomitant Infection of the Golden Hamsters",
    "signal pathway": "Host-parasite interaction",
    "RNAseq/proteomic": null,
    "First author": "Hideo Hasegawa",
    "Affiliation": "Oita University",
    "Journal": "Journal of Parasitology",
    "Year": 2008,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus (among others)",
    "DOI": "10.1645/GE-13471.1",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Infection / Immune",
    "Country": "Japan"
  },
  {
    "Title": "Individual variability and photic entrainment of circadian rhythms in golden spiny mice",
    "signal pathway": "Circadian regulation, SCN entrainment",
    "RNAseq/proteomic": null,
    "First author": "Rotem Cohen",
    "Affiliation": "Tel Aviv University",
    "Journal": "Physiology & Behavior",
    "Year": 2006,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1016/j.physbeh.2005.12.010",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Interspecific Competition and Torpor in Golden Spiny Mice: Two Sides of the Energy-Acquisition Coin",
    "signal pathway": "Torpor regulation, energy metabolism",
    "RNAseq/proteomic": null,
    "First author": "Ofir Levy",
    "Affiliation": "Tel Aviv University",
    "Journal": "Integrative and Comparative Biology",
    "Year": 2011,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1093/icb/icr071",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Intrageneric Phylogeny of Acomys (Rodentia, Muridae) Using Mitochondrial Gene Cytochrome b",
    "signal pathway": "Cytochrome b, mitochondrial phylogenetics",
    "RNAseq/proteomic": null,
    "First author": "Pierre-Olivier Barome",
    "Affiliation": "Centre de Génétique Moléculaire, CNRS",
    "Journal": "Molecular Phylogenetics and Evolution",
    "Year": 1998,
    "Proteomics accession": null,
    "Species": "Acomys spp.",
    "DOI": "10.1006/mpev.1998.0587",
    "Topic": "Evolution",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "France"
  },
  {
    "Title": "Ischemic tolerance and cardiac repair in the spiny mouse (Acomys)",
    "signal pathway": "Angiogenesis, cardiomyocyte regeneration, remodeling",
    "RNAseq/proteomic": "RNAseq (PRJNA692361)",
    "First author": "Tim Koopmans",
    "Affiliation": "Hubrecht Institute",
    "Journal": "NPJ Regenerative Medicine",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/s41536-021-00188-2",
    "Topic": "Regeneration",
    "Organ": "Heart",
    "Disease Model": "Other / Not Specified",
    "Country": "Netherlands"
  },
  {
    "Title": "Large-bodied gastric spirurids predict structure in gastrointestinal helminth community of wild spiny mice",
    "signal pathway": "Host-parasite interaction",
    "RNAseq/proteomic": null,
    "First author": "Jerzy M. Behnke",
    "Affiliation": "University of Nottingham",
    "Journal": "Parasitology",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys dimidiatus",
    "DOI": "10.1017/S0031182024000891",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "UK"
  },
  {
    "Title": "Light interference as a possible stressor altering HSP70 and its gene expression in golden spiny mice",
    "signal pathway": "HSP70 stress response, melatonin",
    "RNAseq/proteomic": null,
    "First author": "Abed E. Zubidat",
    "Affiliation": "University of Haifa",
    "Journal": "Journal of Experimental Biology",
    "Year": 2012,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1242/jeb.073429",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Stress / Behavior",
    "Country": "Israel"
  },
  {
    "Title": "Locomotor activity in common spiny mice (Acomys cahirinus): The effect of light and environmental complexity",
    "signal pathway": "Circadian rhythm, anxiety-related behavior",
    "RNAseq/proteomic": null,
    "First author": "David Eilam",
    "Affiliation": "Tel Aviv University",
    "Journal": "BMC Ecology",
    "Year": 2004,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1186/1472-6785-4-16",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Stress / Behavior",
    "Country": "Israel"
  },
  {
    "Title": "Long-day photoperiod interacts with vasopressin and food restriction to modulate reproductive status",
    "signal pathway": "Vasopressin (Avpr1a), leptin, testosterone signaling",
    "RNAseq/proteomic": null,
    "First author": "Israel Ben-Zaken",
    "Affiliation": "University of Haifa",
    "Journal": "Journal of Experimental Biology",
    "Year": 2013,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1242/jeb.089607",
    "Topic": "Reproduction",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Long-term spatiotemporal stability and changes in the haemoparasite community of spiny mice",
    "signal pathway": "Immune response to haemoparasites (Trypanosoma, Babesia, etc.)",
    "RNAseq/proteomic": null,
    "First author": "Mohammed Alsarraf",
    "Affiliation": "University of Warsaw",
    "Journal": "Parasites & Vectors",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys dimidiatus",
    "DOI": "10.1186/s13071-016-1471-z",
    "Topic": "Immunology",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "Poland"
  },
  {
    "Title": "Macrophages are necessary for epimorphic regeneration in African spiny mice",
    "signal pathway": "Macrophage-mediated inflammation, regeneration, ROS",
    "RNAseq/proteomic": "RNAseq (GSE71761)",
    "First author": "Jennifer Simkin",
    "Affiliation": "University of Kentucky",
    "Journal": "eLife",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.7554/eLife.24623",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  },
  {
    "Title": "Marvels of spiny mouse regeneration: cellular players and their interactions in restoring tissue architecture",
    "signal pathway": "Macrophages, fibroblasts, ECM, Wnt, immune-modulatory signaling",
    "RNAseq/proteomic": null,
    "First author": "Antonio Tomasso",
    "Affiliation": "Stanford University / Osnabrück University / Hubrecht Institute",
    "Journal": "Current Opinion in Genetics & Development",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys",
    "DOI": "10.1016/j.gde.2024.102228",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "Netherlands"
  },
  {
    "Title": "Masking and Temporal Niche Switches in Spiny Mice",
    "signal pathway": "Circadian clock, masking effects, photic entrainment",
    "RNAseq/proteomic": null,
    "First author": "Rotem Cohen",
    "Affiliation": "Tel Aviv University",
    "Journal": "Journal of Biological Rhythms",
    "Year": 2010,
    "Proteomics accession": null,
    "Species": "Acomys russatus, Acomys cahirinus",
    "DOI": "10.1177/0748730409351672",
    "Topic": "Neuroscience",
    "Organ": "Skin",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Maternal creatine homeostasis is altered during gestation in the spiny mouse: is this a metabolic adaptation to pregnancy?",
    "signal pathway": "Creatine synthesis: AGAT, GAMT, CrT1",
    "RNAseq/proteomic": null,
    "First author": "Stacey J. Ellery",
    "Affiliation": "Monash University",
    "Journal": "BMC Pregnancy and Childbirth",
    "Year": 2015,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1186/s12884-015-0524-1",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Maternal creatine supplementation during pregnancy prevents acute and long-term deficits in skeletal muscle after birth asphyxia",
    "signal pathway": "Creatine metabolism, ROS/RNS, myofiber development",
    "RNAseq/proteomic": null,
    "First author": "Domenic A. LaRosa",
    "Affiliation": "Monash University",
    "Journal": "Pediatric Research",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/pr.2016.153",
    "Topic": "Metabolism / Kidney",
    "Organ": "Muscle / Bone",
    "Disease Model": "Ischemia / Stroke",
    "Country": "Australia"
  },
  {
    "Title": "Maternal Creatine Supplementation during Pregnancy Prevents Long-Term Changes in Diaphragm Muscle Structure and Function after Birth Asphyxia",
    "signal pathway": "Creatine metabolism, diaphragm fiber type, ROS",
    "RNAseq/proteomic": null,
    "First author": "Domenic A. LaRosa",
    "Affiliation": "Monash University",
    "Journal": "PLOS ONE",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1371/journal.pone.0149840",
    "Topic": "Metabolism / Kidney",
    "Organ": "Muscle / Bone",
    "Disease Model": "Ischemia / Stroke",
    "Country": "Australia"
  },
  {
    "Title": "Maternal Creatine Supplementation From Mid-Pregnancy Protects the Diaphragm of the Newborn Spiny Mouse From Intrapartum Hypoxia-Induced Damage",
    "signal pathway": "Creatine, ROS, muscle atrophy markers (MuRF1, myostatin)",
    "RNAseq/proteomic": null,
    "First author": "David J. Cannata",
    "Affiliation": "Deakin University",
    "Journal": "Pediatric Research",
    "Year": 2010,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1203/PDR.0b013e3181f1c21d",
    "Topic": "Other",
    "Organ": "Muscle / Bone",
    "Disease Model": "Ischemia / Stroke",
    "Country": "Australia"
  },
  {
    "Title": "Maternal creatine: does it reach the fetus and improve survival after an acute hypoxic episode in the spiny mouse (Acomys cahirinus)?",
    "signal pathway": "Creatine uptake, ATP buffering, ROS scavenging",
    "RNAseq/proteomic": null,
    "First author": "Zoe Ireland",
    "Affiliation": "Monash University",
    "Journal": "American Journal of Obstetrics and Gynecology",
    "Year": 2008,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.ajog.2007.10.790",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Maternal dexamethasone treatment at midgestation reduces nephron number and alters renal gene expression in the fetal spiny mouse",
    "signal pathway": "BMP4, TGF-β1, Gremlin, Bax (branching morphogenesis, apoptosis)",
    "RNAseq/proteomic": null,
    "First author": "Hayley Dickinson",
    "Affiliation": "Monash University",
    "Journal": "American Journal of Physiology - Regulatory, Integrative and Comparative Physiology",
    "Year": 2007,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1152/ajpregu.00481.2006",
    "Topic": "Metabolism / Kidney",
    "Organ": "Kidney",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Maternal Dietary Creatine Supplementation Does Not Alter the Capacity for Creatine Synthesis in the Newborn Spiny Mouse",
    "signal pathway": "Creatine synthesis pathway: AGAT, GAMT, SLC6A8",
    "RNAseq/proteomic": null,
    "First author": "Hayley Dickinson",
    "Affiliation": "Monash Institute of Medical Research",
    "Journal": "Reproductive Sciences",
    "Year": 2013,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1177/1933719113477478",
    "Topic": "Reproduction",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Matrisomal components involved in regenerative wound healing in axolotl and Acomys: implications for biomaterial development",
    "signal pathway": "ECM remodeling, matrisome, MMP2, MMP9, Wnt, MAPK signaling, proteoglycans",
    "RNAseq/proteomic": "review",
    "First author": "Nancy Avila-Martinez",
    "Affiliation": "Radboud University Medical Center",
    "Journal": "Biomaterials Science",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys spp.",
    "DOI": "10.1039/d3bm00835e",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "Netherlands"
  },
  {
    "Title": "Molecular and histologic outcomes following spinal cord injury in spiny mice, Acomys cahirinus",
    "signal pathway": "Inflammation, fibrosis (Serpine1, Plau, Timp1), regeneration (Bmp2, GDNF, Shh)",
    "RNAseq/proteomic": null,
    "First author": "K.A. Streeter",
    "Affiliation": "University of Florida",
    "Journal": "Journal of Comparative Neurology",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1002/cne.24836",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Multiple radiations of spiny mice (Rodentia: Acomys) in dry open habitats of Afro-Arabia",
    "signal pathway": "Phylogenetics - mtDNA, multilocus markers",
    "RNAseq/proteomic": null,
    "First author": "T. Aghová",
    "Affiliation": "Institute of Vertebrate Biology, Czech Academy of Sciences",
    "Journal": "BMC Evolutionary Biology",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys spp.",
    "DOI": "10.1186/s12862-019-1380-9",
    "Topic": "Evolution",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Czech Republic"
  },
  {
    "Title": "Neural crest cells give rise to non-myogenic mesenchymal tissue in the adult murid ear pinna",
    "signal pathway": "Wnt, Bmp5, neural crest lineage tracing",
    "RNAseq/proteomic": null,
    "First author": "Robyn S. Allen",
    "Affiliation": "University of Kentucky",
    "Journal": "bioRxiv (preprint)",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Mus musculus",
    "DOI": "10.1101/2023.08.06.552195",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Nutritionally Induced Diabetes in Desert Rodents: Acomys cahirinus and Psammomys obesus",
    "signal pathway": "Insulin secretion, GLUT2, glucokinase, β-cell apoptosis",
    "RNAseq/proteomic": null,
    "First author": "Eleazar Shafrir",
    "Affiliation": "Hadassah University Hospital",
    "Journal": "ILAR Journal",
    "Year": 2006,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Psammomys obesus",
    "DOI": "10.1093/ilar.47.3.212",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Diabetes / Metabolic Syndrome",
    "Country": "Israel"
  },
  {
    "Title": "Older spiny mice (Acomys cahirinus) have delayed and spatially heterogenous ear wound regeneration",
    "signal pathway": "Myh3, muscle/collagen/adipocyte regeneration markers",
    "RNAseq/proteomic": null,
    "First author": "Justin A. Varholick",
    "Affiliation": "University of Florida",
    "Journal": "Biology Open",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1242/bio.059289",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "On heights and plains: How rodents from different habitats cope with three-dimensional environments",
    "signal pathway": "Not specified – behavioral ecology study",
    "RNAseq/proteomic": null,
    "First author": "Iris Berkovitz",
    "Affiliation": "Tel Aviv University",
    "Journal": "Ecology and Evolution",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Apodemus, Mus, Rattus",
    "DOI": "10.1002/ece3.6614",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Opioid withdrawal behavior in spiny mice: A novel preclinical model of neonatal opioid withdrawal syndrome (NOWS)",
    "signal pathway": "Opioid receptor signaling, neurodevelopmental markers",
    "RNAseq/proteomic": null,
    "First author": "Amanda Kent",
    "Affiliation": "Emory University",
    "Journal": "Behavioural Brain Research",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.bbr.2023.114585",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Osteoderms in a mammal the spiny mouse Acomys and the independent evolution of dermal armor",
    "signal pathway": "BMP, FGF, Hedgehog, Wnt, Osteoblast differentiation, Sclerostin, Runx2-Sp7-Osteocrin pathway",
    "RNAseq/proteomic": "RNAseq (GSE113081)",
    "First author": "Malcolm Maden",
    "Affiliation": "University of Florida",
    "Journal": "iScience",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.isci.2023.106779",
    "Topic": "Other",
    "Organ": "Skin",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Overnutrition in spiny mice (Acomys cahirinus): β-cell expansion and diabetes on fat-rich diet, protective thyroid hormone on sucrose-rich diet",
    "signal pathway": "Insulin signaling, β-cell expansion, thyroid hormone regulation",
    "RNAseq/proteomic": null,
    "First author": "Eleazar Shafrir",
    "Affiliation": "Hadassah University Hospital",
    "Journal": "Hormone and Metabolic Research",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1055/s-0043-101901",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Diabetes / Metabolic Syndrome",
    "Country": "Israel"
  },
  {
    "Title": "Perfect chronic skeletal muscle regeneration in adult spiny mice, Acomys cahirinus",
    "signal pathway": "Myogenic regulatory factors (Myf5, MyoD, Myogenin), Notch, Wnt, TGFβ-1, IL-4/IL-13",
    "RNAseq/proteomic": null,
    "First author": "Malcolm Maden",
    "Affiliation": "University of Florida",
    "Journal": "Scientific Reports",
    "Year": 2018,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/s41598-018-27178-7",
    "Topic": "Regeneration",
    "Organ": "Muscle / Bone",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Photoperiodicity and increasing salinity as environmental cues for reproduction in desert adapted rodents",
    "signal pathway": "Vasopressin, aldosterone, reproductive hormone signaling",
    "RNAseq/proteomic": null,
    "First author": "Elena Bukovetzky",
    "Affiliation": "University of Haifa",
    "Journal": "Hormones and Behavior",
    "Year": 2012,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.yhbeh.2011.10.006",
    "Topic": "Reproduction",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Postpartum ovulation and early pregnancy in the menstruating spiny mouse, Acomys cahirinus",
    "signal pathway": "Estradiol, progesterone signaling",
    "RNAseq/proteomic": null,
    "First author": "Jarrod McKenna",
    "Affiliation": "Monash University",
    "Journal": "Scientific Reports",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/s41598-021-84361-z",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "Regeneration-Competent and -Incompetent Murids Differ in Neutrophil Quantity and Function",
    "signal pathway": "Inflammation, ROS, phagocytosis",
    "RNAseq/proteomic": null,
    "First author": "Jennifer L. Cyr",
    "Affiliation": "University of Georgia",
    "Journal": "Integrative and Comparative Biology",
    "Year": 2019,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, A. kempi, A. percivali, Mus musculus",
    "DOI": "10.1093/icb/icz023",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Infection / Immune",
    "Country": "Georgia"
  },
  {
    "Title": "Renal dysfunction in early adulthood following birth asphyxia in male spiny mice",
    "signal pathway": "Creatine metabolism, oxidative stress",
    "RNAseq/proteomic": null,
    "First author": "Stacey J. Ellery",
    "Affiliation": "Hudson Institute of Medical Research",
    "Journal": "Pediatric Research",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/pr.2016.268",
    "Topic": "Metabolism / Kidney",
    "Organ": "Kidney",
    "Disease Model": "Ischemia / Stroke",
    "Country": "Australia"
  },
  {
    "Title": "Reproductive aging and menopause-like transition in the menstruating spiny mouse",
    "signal pathway": "Ovarian reserve depletion, estradiol/testosterone signaling",
    "RNAseq/proteomic": null,
    "First author": "Nadia Bellofiore",
    "Affiliation": "Hudson Institute of Medical Research",
    "Journal": "Human Reproduction",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1093/humrep/deab215",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "Retinal neuroanatomy of two emerging model organisms, the spiny mouse and Mongolian gerbil",
    "signal pathway": "Retinal cell markers (IHC-based)",
    "RNAseq/proteomic": null,
    "First author": "Jessica D. Bills",
    "Affiliation": "University of Kentucky",
    "Journal": "Experimental Eye Research",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys dimidiatus, Meriones unguiculatus",
    "DOI": "10.1016/j.exer.2024.110055",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Rewired glycosylation activity promotes scarless regeneration and functional recovery in spiny mice after complete spinal cord transection",
    "signal pathway": "Glycosylation pathways, proteoglycan biosynthesis (b3gnt7), axon regeneration",
    "RNAseq/proteomic": "RNAseq (PRJNA766650)",
    "First author": "Joana Nogueira-Rodrigues",
    "Affiliation": "University of Porto, i3S",
    "Journal": "Developmental Cell",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.devcel.2021.12.008",
    "Topic": "Regeneration",
    "Organ": "Other",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "Portugal"
  },
  {
    "Title": "Rodents in open space adjust their behavioral response to the different risk levels during barn-owl attack",
    "signal pathway": "Neuro-behavioral response, stress hormone regulation (not molecular pathways)",
    "RNAseq/proteomic": null,
    "First author": "Shahaf Edut",
    "Affiliation": "Tel Aviv University",
    "Journal": "BMC Ecology",
    "Year": 2003,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1186/1472-6785-3-10",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Stress / Behavior",
    "Country": "Israel"
  },
  {
    "Title": "Skin fragility in the wild-derived, inbred mouse strain Mus pahari EiJ",
    "signal pathway": "ECM structure, collagen and elastin fiber abnormalities",
    "RNAseq/proteomic": null,
    "First author": "C. Herbert Pratt",
    "Affiliation": "The Jackson Laboratory",
    "Journal": "Experimental and Molecular Pathology",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Mus pahari",
    "DOI": "10.1016/j.yexmp.2016.12.009",
    "Topic": "Other",
    "Organ": "Skin",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Skin shedding and tissue regeneration in African spiny mice (Acomys)",
    "signal pathway": "Wound contraction, hair follicle regeneration",
    "RNAseq/proteomic": null,
    "First author": "Ashley W. Seifert",
    "Affiliation": "University of Florida",
    "Journal": "Nature",
    "Year": 2012,
    "Proteomics accession": null,
    "Species": "Acomys kempi, Acomys percivali",
    "DOI": "10.1038/nature11499",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Spatial transcriptomics reveals asymmetric cellular responses to injury in the regenerating spiny mouse (Acomys) ear",
    "signal pathway": "Immune regulation, ECM remodeling, blastema formation",
    "RNAseq/proteomic": "Spatial transcriptomics/scRNAseq (PRJNA898313, GSE224879, GSE224433)",
    "First author": "Henriëtte van Beijnum",
    "Affiliation": "Hubrecht Institute-KNAW",
    "Journal": "Genome Research",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1101/gr.277538.122",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "Netherlands"
  },
  {
    "Title": "Species-typical group size differentially influences social reward neural circuitry during nonreproductive social interactions",
    "signal pathway": "Oxytocin (OT), Tyrosine Hydroxylase (TH) in PVN and VTA",
    "RNAseq/proteomic": null,
    "First author": "Jose A. Gonzalez Abreu",
    "Affiliation": "Emory University",
    "Journal": "iScience",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Meriones unguiculatus",
    "DOI": "10.1016/j.isci.2022.104230",
    "Topic": "Reproduction",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Spiny mice (Acomys cahirinus) do not respond to thymus-independent type 2 antigens",
    "signal pathway": "Immune response; B cell and T cell signaling",
    "RNAseq/proteomic": null,
    "First author": "Anthony Pennello",
    "Affiliation": "Rider University",
    "Journal": "Developmental & Comparative Immunology",
    "Year": 2006,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Mus musculus, Meriones",
    "DOI": "10.1016/j.dci.2006.03.007",
    "Topic": "Immunology",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  },
  {
    "Title": "Spiny mice (Acomys) cells fail to engraft in NOD scid gamma",
    "signal pathway": "Immune cell engraftment and hematopoiesis",
    "RNAseq/proteomic": null,
    "First author": "Janak Gaire",
    "Affiliation": "University of Florida",
    "Journal": "PLoS ONE",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1371/journal.pone.0286000",
    "Topic": "Immunology",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  },
  {
    "Title": "Spiny mice (Acomys) exhibit attenuated hallmarks of aging and rapid cell turnover after UV exposure in the skin epidermis",
    "signal pathway": "Keratin 14/10, senescence, inflammatory cytokines",
    "RNAseq/proteomic": null,
    "First author": "Wesley Wong",
    "Affiliation": "Northeastern University",
    "Journal": "PLoS ONE",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Mus musculus",
    "DOI": "10.1371/journal.pone.0241617",
    "Topic": "Immunology",
    "Organ": "Skin",
    "Disease Model": "Aging",
    "Country": "USA"
  },
  {
    "Title": "Spiny mice activate unique transcriptional programs after severe kidney injury regenerating organ function without fibrosis",
    "signal pathway": "Fibrosis, nephron regeneration, early response transcriptional programs",
    "RNAseq/proteomic": "RNAseq (GSE168876)",
    "First author": "Daryl M. Okamura",
    "Affiliation": "Seattle Children’s Research Institute",
    "Journal": "iScience",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Mus musculus",
    "DOI": "10.1016/j.isci.2021.103269",
    "Topic": "Regeneration",
    "Organ": "Kidney",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Spiny mice are primed but fail to regenerate volumetric skeletal muscle loss injuries",
    "signal pathway": "Myogenesis, muscle stem cell signaling (eMHC expression), ECM remodeling",
    "RNAseq/proteomic": null,
    "First author": "Mackenzie L. Davenport",
    "Affiliation": "University of Florida",
    "Journal": "Skeletal Muscle",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1186/s13395-024-00358-y",
    "Topic": "Regeneration",
    "Organ": "Muscle / Bone",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Spiny Mice Modulate Eumelanin to Pheomelanin Ratio to Achieve Cryptic Coloration in ‘‘Evolution Canyon,’’ Israel",
    "signal pathway": "Melanin biosynthesis",
    "RNAseq/proteomic": null,
    "First author": "Natarajan Singaravelan",
    "Affiliation": "University of Haifa",
    "Journal": "PLoS ONE",
    "Year": 2010,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1371/journal.pone.0008708",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Stroke-induced neuroplasticity in spiny mice in the absence of tissue regeneration",
    "signal pathway": "Neuroplasticity, connectome remodeling",
    "RNAseq/proteomic": null,
    "First author": "Benjamin M. Kidd",
    "Affiliation": "University of Florida",
    "Journal": "npj Regenerative Medicine",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/s41536-024-00386-8",
    "Topic": "Regeneration",
    "Organ": "Brain / CNS",
    "Disease Model": "Ischemia / Stroke",
    "Country": "USA"
  },
  {
    "Title": "Symmetry breaking of tissue mechanics in wound induced hair follicle regeneration of laboratory and spiny mice",
    "signal pathway": "Twist1, Wnt/β-catenin, Edar, Shh, Turing morphogenesis",
    "RNAseq/proteomic": "Array/RNAseq/scRNAseq (GSE50418, GSE159939)",
    "First author": "Hans I-Chen Harn",
    "Affiliation": "Keck School of Medicine, USC",
    "Journal": "Nature Communications",
    "Year": 2021,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Mus musculus",
    "DOI": "10.1038/s41467-021-22822-9",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Sympatric incipient speciation of spiny mice Acomys at “Evolution Canyon,” Israel",
    "signal pathway": "None (evolutionary biology, genetic diversity)",
    "RNAseq/proteomic": "mtDNA (JN571139–JN571155)",
    "First author": "Yarin Hadid",
    "Affiliation": "University of Haifa",
    "Journal": "PNAS",
    "Year": 2014,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1073/pnas.1324212111",
    "Topic": "Evolution",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Sympatric speciation of spiny mice, Acomys, unfolded transcriptomically at Evolution Canyon, Israel",
    "signal pathway": "Heat-shock proteins, DNA repair, ATP metabolism (via RNAseq)",
    "RNAseq/proteomic": null,
    "First author": "Kexin Li",
    "Affiliation": "Institute of Evolution, University of Haifa",
    "Journal": "PNAS",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1073/pnas.1608777113",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Sympatric speciation of the spiny mouse from Evolution Canyon in Israel substantiated genomically and methylomically",
    "signal pathway": "Olfactory receptors, circadian rhythm genes (epigenetic regulation)",
    "RNAseq/proteomic": "Genome/methylome (PRJNA783778/GSE223748)",
    "First author": "Yinjia Wang",
    "Affiliation": "Zhengzhou University",
    "Journal": "PNAS",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1073/pnas.2121822119",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "China"
  },
  {
    "Title": "That’s hot: golden spiny mice display torpor even at high ambient temperatures",
    "signal pathway": "Thermogenesis, metabolic rate, torpor regulation",
    "RNAseq/proteomic": null,
    "First author": "Kirsten Grimpo",
    "Affiliation": "Philipps-Universität Marburg",
    "Journal": "Journal of Comparative Physiology B",
    "Year": 2013,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1007/s00360-012-0721-4",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Germany"
  },
  {
    "Title": "The Biology and Husbandry of the African Spiny Mouse (Acomys cahirinus) and the Research Uses of a Laboratory Colony",
    "signal pathway": "Developmental physiology, diabetes, neurogenesis, regeneration (review)",
    "RNAseq/proteomic": null,
    "First author": "Cheryl L. Haughton",
    "Affiliation": "University of Kentucky",
    "Journal": "JAALAS",
    "Year": 2016,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, A. russatus, A. dimidiatus, A. percivali",
    "DOI": null,
    "Topic": "Regeneration",
    "Organ": "Brain / CNS",
    "Disease Model": "Diabetes / Metabolic Syndrome",
    "Country": "USA"
  },
  {
    "Title": "The Effect of the Lunar Cycle on Fecal Cortisol Metabolite Levels and Foraging Ecology of Nocturnally and Diurnally Active Spiny Mice",
    "signal pathway": "Glucocorticoid response to environmental stressors (moon phase)",
    "RNAseq/proteomic": null,
    "First author": "Roee Gutman",
    "Affiliation": "Tel Aviv University",
    "Journal": "PLoS ONE",
    "Year": 2011,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Acomys russatus",
    "DOI": "10.1371/journal.pone.0023446",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Aging",
    "Country": "Israel"
  },
  {
    "Title": "The effects of dexamethasone administered during pregnancy on the postpartum spiny mouse ovary",
    "signal pathway": "Apoptosis (caspase-3, Bax, Bcl-2), Autophagy (Beclin1, Lamp1), Glucocorticoid receptor",
    "RNAseq/proteomic": null,
    "First author": "Monika Hułas-Stasiak",
    "Affiliation": "Maria Curie-Skłodowska University",
    "Journal": "PLoS ONE",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1371/journal.pone.0183528",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Poland"
  },
  {
    "Title": "The effects of lighting conditions and food restriction paradigms on locomotor activity of common spiny mice, Acomys cahirinus",
    "signal pathway": "Circadian rhythm, food-entrainable oscillator (FEO), light-entrainable oscillator (LEO)",
    "RNAseq/proteomic": null,
    "First author": "Christopher C. Chabot",
    "Affiliation": "Plymouth State University",
    "Journal": "Journal of Circadian Rhythms",
    "Year": 2012,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1186/1740-3391-10-6",
    "Topic": "Neuroscience",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "The effects of sex, age and commensal way of life on levels of fecal glucocorticoid metabolites in spiny mice (Acomys cahirinus)",
    "signal pathway": "Stress hormone regulation (glucocorticoids)",
    "RNAseq/proteomic": null,
    "First author": "M. Nováková",
    "Affiliation": "Charles University, Prague",
    "Journal": "Physiology & Behavior",
    "Year": 2008,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.physbeh.2008.05.017",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Stress / Behavior",
    "Country": "Czech Republic"
  },
  {
    "Title": "THE IMPACT OF β-ADRENERGIC BLOCKADE ON DAILY RHYTHMS OF MELATONIN AND BODY TEMPERATURE OF GOLDEN SPINY MICE ACOMYS RUSSATUS",
    "signal pathway": "β-adrenergic signaling, melatonin synthesis, thermoregulation",
    "RNAseq/proteomic": null,
    "First author": "A. Haim",
    "Affiliation": "University of Haifa at Oranim",
    "Journal": "Life Sciences",
    "Year": 1997,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1016/S0024-3205(97)00535-3",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "The Placental Response to Excess Maternal Glucocorticoid Exposure Differs Between the Male and Female Conceptus in Spiny Mice",
    "signal pathway": "IGF1, IGF1R, SLC2A1, GCM1, MAP2K1 (placental development)",
    "RNAseq/proteomic": null,
    "First author": "Bree A. O’Connell",
    "Affiliation": "Monash Institute of Medical Research",
    "Journal": "Biology of Reproduction",
    "Year": 2011,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1095/biolreprod.111.093369",
    "Topic": "Reproduction",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "The spiny mouse (Acomys cahirinus) completes nephrogenesis before birth",
    "signal pathway": "Renal development pathways, nephrogenesis (ureteric bud-mesenchyme interactions)",
    "RNAseq/proteomic": null,
    "First author": "Hayley Dickinson",
    "Affiliation": "Monash University",
    "Journal": "American Journal of Physiology-Renal Physiology",
    "Year": 2005,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1152/ajprenal.00400.2004",
    "Topic": "Metabolism / Kidney",
    "Organ": "Kidney",
    "Disease Model": "Other / Not Specified",
    "Country": "Australia"
  },
  {
    "Title": "Three new karyotypes extend a Robertsonian fan in Ethiopian spiny mice of the genus Acomys",
    "signal pathway": "Chromosomal evolution, Robertsonian translocation",
    "RNAseq/proteomic": null,
    "First author": "L.A. Lavrenchenko",
    "Affiliation": "A.N. Severtsov Institute of Ecology and Evolution",
    "Journal": "Comparative Cytogenetics",
    "Year": 2011,
    "Proteomics accession": null,
    "Species": "Acomys spp. (Ethiopian populations)",
    "DOI": "10.3897/CompCytogen.v5i5.1252",
    "Topic": "Other",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Tissue resident macrophages specifically express Lactotransferrin and Vegfc during ear pinna regeneration in spiny mice",
    "signal pathway": "VEGFC, PDGFA, LTF; macrophage-regulated regeneration signaling",
    "RNAseq/proteomic": "scRNAseq (GSE182141 )",
    "First author": "Jennifer Simkin",
    "Affiliation": "University of Kentucky",
    "Journal": "Developmental Cell",
    "Year": 2024,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, Mus musculus",
    "DOI": "10.1016/j.devcel.2023.12.017",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Other / Not Specified",
    "Country": "USA"
  },
  {
    "Title": "Two strategies for coping with food shortage in desert golden spiny mice",
    "signal pathway": "Metabolic adaptation, activity regulation under starvation",
    "RNAseq/proteomic": null,
    "First author": "Roee Gutman",
    "Affiliation": "Tel Aviv University",
    "Journal": "Physiology & Behavior",
    "Year": 2007,
    "Proteomics accession": null,
    "Species": "Acomys russatus",
    "DOI": "10.1016/j.physbeh.2006.08.033",
    "Topic": "Metabolism / Kidney",
    "Organ": "Other",
    "Disease Model": "Other / Not Specified",
    "Country": "Israel"
  },
  {
    "Title": "Understanding the behavioural phenotype of the precocial spiny mouse",
    "signal pathway": "Neurological development, sensorimotor and anxiety pathways",
    "RNAseq/proteomic": null,
    "First author": "Udani Ratnayake",
    "Affiliation": "Monash University / University of Melbourne",
    "Journal": "Behavioural Brain Research",
    "Year": 2014,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.bbr.2014.08.035",
    "Topic": "Neuroscience",
    "Organ": "Brain / CNS",
    "Disease Model": "Stress / Behavior",
    "Country": "Australia"
  },
  {
    "Title": "Universal DNA methylation age across mammalian tissues",
    "signal pathway": "Polycomb Repressive Complex 2, development, cancer, obesity, longevity pathways",
    "RNAseq/proteomic": "DNA methylation (GSE223748)",
    "First author": "Steve Horvath",
    "Affiliation": "University of California, Los Angeles",
    "Journal": "Nature Aging",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus (among 185 mammals)",
    "DOI": "10.1038/s43587-023-00462-6",
    "Topic": "Epigenetics",
    "Organ": "Other",
    "Disease Model": "Diabetes / Metabolic Syndrome",
    "Country": "USA"
  },
  {
    "Title": "Variation in the helminth community structure in spiny mice (Acomys dimidiatus)",
    "signal pathway": "Host-parasite immune interaction",
    "RNAseq/proteomic": null,
    "First author": "Mohammed Alsarraf",
    "Affiliation": "University of Warsaw",
    "Journal": "Parasitology Research",
    "Year": 2017,
    "Proteomics accession": null,
    "Species": "Acomys dimidiatus",
    "DOI": "10.1007/s00436-017-5332-3",
    "Topic": "Immunology",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "Poland"
  },
  {
    "Title": "β-Hydroxy-β-Methylbutyrate (HMB) Supplementation Prevents Bone Loss during Pregnancy",
    "signal pathway": "Bone metabolism, BMP-2, MMP-13, TIMP2, VEGF",
    "RNAseq/proteomic": null,
    "First author": "Ewa Tomaszewska",
    "Affiliation": "University of Life Sciences in Lublin",
    "Journal": "Nutrients",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.3390/nu14132599",
    "Topic": "Metabolism / Kidney",
    "Organ": "Muscle / Bone",
    "Disease Model": "Bone / Joint Disorders",
    "Country": "Poland"
  },
  {
    "Title": "Characteristics of the endometrium in menstruating species: lessons learned from the animal kingdom",
    "signal pathway": "MMPs, prostaglandins, progesterone signaling",
    "RNAseq/proteomic": "No",
    "First author": "Nadia Bellofiore",
    "Affiliation": "Hudson Institute of Medical Research",
    "Journal": "Human Reproduction Update",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus, human",
    "DOI": "10.1093/humupd/dmac021",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "From grouping and cooperation to menstruation: Spiny mice (Acomys cahirinus) are an emerging mammalian model for sociality and beyond",
    "signal pathway": "Oxytocin, HPA axis, progesterone withdrawal",
    "RNAseq/proteomic": "No",
    "First author": "Nadia Bellofiore",
    "Affiliation": "Hudson Institute of Medical Research",
    "Journal": "Hormones and Behavior",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.yhbeh.2023.105478",
    "Topic": "Reproduction",
    "Organ": "Reproductive",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "Australia"
  },
  {
    "Title": "Insights into the regeneration of skin from Acomys, the spiny mouse",
    "signal pathway": "Wnt, Fgf, Tgf-β, Hippo-YAP, immune modulation",
    "RNAseq/proteomic": "Referenced (RNAseq, proteomic in other studies)",
    "First author": "Sara Gorski",
    "Affiliation": "University of Florida",
    "Journal": "Current Opinion in Genetics & Development",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.gde.2021.11.009",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  },
  {
    "Title": "Model systems for regeneration: the spiny mouse, Acomys cahirinus",
    "signal pathway": "Wnt, immune signaling, ECM remodeling",
    "RNAseq/proteomic": "Overview only",
    "First author": "Sara Gorski",
    "Affiliation": "University of Florida",
    "Journal": "Developmental Dynamics",
    "Year": 2022,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1002/dvdy.483",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  },
  {
    "Title": "Modulating Cellular Responses to Mechanical Forces to Promote Wound Regeneration",
    "signal pathway": "YAP/TAZ, Piezo1, mechanotransduction, actin cytoskeleton",
    "RNAseq/proteomic": "No (review)",
    "First author": "Sara Gorski",
    "Affiliation": "University of Florida",
    "Journal": "Frontiers in Cell and Developmental Biology",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys, other models",
    "DOI": "10.3389/fcell.2023.1134488",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Fibrosis / Wound Healing",
    "Country": "USA"
  },
  {
    "Title": "Monkeys, mice and menses: the bloody anomaly of the spiny mouse",
    "signal pathway": "Endometrial remodeling, progesterone, inflammation",
    "RNAseq/proteomic": "No",
    "First author": "Kate McCaffrey",
    "Affiliation": "Monash University",
    "Journal": "Nature Reviews Endocrinology",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1038/s41574-020-00426-y",
    "Topic": "Immunology",
    "Organ": "Other",
    "Disease Model": "Infection / Immune",
    "Country": "Australia"
  },
  {
    "Title": "Regeneration in the spiny mouse, Acomys, a new mammalian model",
    "signal pathway": "Wnt, BMP, immune regulation, regeneration markers",
    "RNAseq/proteomic": "Referenced",
    "First author": "Ashley W. Seifert",
    "Affiliation": "University of Florida",
    "Journal": "Current Opinion in Genetics & Development",
    "Year": 2018,
    "Proteomics accession": null,
    "Species": "Acomys cahirinus",
    "DOI": "10.1016/j.gde.2018.06.001",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  },
  {
    "Title": "The African spiny mouse (Acomys spp.) as an emerging model for development and regeneration",
    "signal pathway": "Various (skin, muscle, kidney regeneration, menstruation)",
    "RNAseq/proteomic": "Overview",
    "First author": "Sara Gorski",
    "Affiliation": "University of Florida",
    "Journal": "Genesis",
    "Year": 2020,
    "Proteomics accession": null,
    "Species": "Acomys spp.",
    "DOI": "10.1002/dvg.23321",
    "Topic": "Regeneration",
    "Organ": "Skin",
    "Disease Model": "Menstrual / Reproductive Disorders",
    "Country": "USA"
  },
  {
    "Title": "The blastema and epimorphic regeneration in mammals",
    "signal pathway": "Blastema signaling, immune modulation, fibroblast heterogeneity",
    "RNAseq/proteomic": "Referenced (multiple)",
    "First author": "Sara Gorski",
    "Affiliation": "University of Florida",
    "Journal": "Developmental Dynamics",
    "Year": 2023,
    "Proteomics accession": null,
    "Species": "Acomys, other mammals",
    "DOI": "10.1002/dvdy.578",
    "Topic": "Regeneration",
    "Organ": "Immune system",
    "Disease Model": "Infection / Immune",
    "Country": "USA"
  }
];